DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dispenser;
DROP TABLE IF EXISTS water;
DROP TABLE IF EXISTS quality;
DROP TABLE IF EXISTS water_consumption;

CREATE TABLE users (
    name TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    height FLOAT NOT NULL,
    hair_length TEXT NOT NULL
);

CREATE TABLE dispenser (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fill_value REAL NOT NULL
);

CREATE TABLE water (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature FLOAT NOT NULL,
    preparation_date DATE NOT NULL
);

CREATE TABLE water_consumption (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumption FLOAT NOT NULL
);

CREATE TABLE quality (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    water_quality REAL NOT NULL,
    dispenser_quality REAL NOT NULL,
    filter_quality REAL NOT NULL
);