DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dispenser;
DROP TABLE IF EXISTS water;

CREATE TABLE users (
    name TEXT PRIMARY KEY,
    height FLOAT NOT NULL,
    hair_length TEXT NOT NULL
);

CREATE TABLE dispenser (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fill_value REAL NOT NULL
);

CREATE TABLE water (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature FLOAT NOT NULL,
    preparation_date DATE NOT NULL
);